### ISSUE TITLE
webpack i18next errors

### ISSUE THREAD

**Issue by jdevega** [redradix/redux-base-app#18]
ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'react-i18next/lib' in /Users/joseluis/workspace/gmvfop-box/gmv-fop/src
 @ ./src/index.js 23:11-39

ERROR in ./src/utils/i18n.js
Module not found: Error: Cannot resolve module 'i18next/lib' in /Users/joseluis/workspace/gmvfop-box/gmv-fop/src/utils
 @ ./src/utils/i18n.js 7:11-33

ERROR in ./src/components/common/header.js
Module not found: Error: Cannot resolve module 'react-i18next/lib' in /Users/joseluis/workspace/gmvfop-box/gmv-fop/src/components/common
 @ ./src/components/common/header.js 18:11-39

ERROR in ./src/components/auth/login.js
Module not found: Error: Cannot resolve module 'react-i18next/lib' in /Users/joseluis/workspace/gmvfop-box/gmv-fop/src/components/auth
 @ ./src/components/auth/login.js 26:11-39

ERROR in ./src/components/auth/register.js
Module not found: Error: Cannot resolve module 'react-i18next/lib' in /Users/joseluis/workspace/gmvfop-box/gmv-fop/src/components/auth
 @ ./src/components/auth/register.js 26:11-39

**Comment by acontreras89** [comment]
This has been fixed in 4a846de thanks to @julianitor! :clap:
