### ISSUE TITLE
Add crossenv

### ISSUE THREAD

**Issue by kanedaki** [redradix/redux-base-app#25]
https://www.npmjs.com/package/cross-env

**Comment by acontreras89** [comment]
`cross-env` seems to address a really particular edge-case (windows + the need to pass inline environment variables). We're already using `dotenv` to allow environment variables to be stored in a file, which is supposed to work right for windows.

I think we should review our scripts instead, and avoid passing inline env vars altogether.

Now, if you want to have this functionality at hand when installing the base application, can I suggest creating [a cherry](https://github.com/redradix/redux-base-app/blob/ac-cherries/docs/cherries.md) for it?

**Comment by kanedaki** [comment]
I was only concern about not working on windows. If it is working on windows, it is find for me. Please, if you can, check it out, so we don't find this problem later.
