### ISSUE TITLE
Meter estructura de atomic design y presentacionales/contexto/interaccion/composicion

### ISSUE THREAD

**Issue by kanedaki** [redradix/redux-base-app#30]
Con la diferenciacion entre comunes y especificos

**Comment by acontreras89** [comment]
Hello @kanedaki,

in commit 53c9edeaf55577f6e5ba09126227b57e957eb828 I rearranged components into four folders, `connected`, `layouts`, `controllers` and `views`, which should be used to place context, composition, interaction and presentation components respectively.

This folder structure has worked greatly for me so far, with slight project-dependant changes.

If you feel like we're missing something, please let me know what you would add, and the motivation for it.

**Comment by kanedaki** [comment]
Si, me referia al hecho de meter dentro de los presentacionales, la estructura de atomic design o al menos, atomos y moleculas.

**Comment by kanedaki** [comment]
BTW, sorry, pero me horripilan los nombres. Lo he intentado con el proyecto de antevenio durante un par de dias y no me mola. Me recuerda a mvc y no me parece que describan claramente lo que hacen. 
Podriamos volver a llamarlos:
context
composition
interaction
presentation

Thanks y sorry por la confusion
