### ISSUE TITLE
fetch browser compatibility

### ISSUE THREAD

**Issue by jdevega** [redradix/redux-base-app#6]
We are using fetch to call to the server API, but the fetch API is not compatible with some [desktop/mobile browsers](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Browser_compatibility)

**Comment by jdevega** [comment]
This is GitHub fetch polyfill implementation https://github.com/github/fetch

**Comment by cdelaorden** [comment]
@jdevega I see `isomorphic-fetch` in package.json, which is itself based on the polyfill you're mentioning.

https://github.com/matthew-andrews/isomorphic-fetch

**Comment by jdevega** [comment]
Ok, closing !
